"""thermal table name lowercase

Revision ID: 0524bd5b4d27
Revises: 
Create Date: 2024-01-01 20:43:59.744707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0524bd5b4d27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('manufacturer_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('manufacturer_name')
    )
    op.create_table('valid_postal',
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.PrimaryKeyConstraint('postal_code')
    )
    op.create_table('household',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('household_type', sa.String(length=256), nullable=False),
    sa.Column('postal', sa.CHAR(length=5), nullable=False),
    sa.Column('sqft', sa.Integer(), nullable=False),
    sa.Column('public_utilities', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['postal'], ['valid_postal.postal_code'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('appliance',
    sa.Column('seq_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('manufacturer', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=True),
    sa.Column('BTU', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['household.email'], ),
    sa.ForeignKeyConstraint(['manufacturer'], ['manufacturer.manufacturer_name'], ),
    sa.PrimaryKeyConstraint('seq_num', 'email')
    )
    op.create_table('power_generator',
    sa.Column('seq_num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('kilowatt_hours', sa.Integer(), nullable=False),
    sa.Column('battery_storage', sa.Integer(), nullable=True),
    sa.Column('energy_source', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['household.email'], ),
    sa.PrimaryKeyConstraint('seq_num', 'email')
    )
    op.create_table('thermal',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('thermal_type', sa.String(length=256), nullable=False),
    sa.Column('setting', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['household.email'], ),
    sa.PrimaryKeyConstraint('email', 'thermal_type')
    )
    op.create_table('air_handler',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('RPM', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email', 'seq_num'], ['appliance.email', 'appliance.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'seq_num')
    )
    op.create_table('water_heater',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('tank_size', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.Column('energy_source', sa.String(length=256), nullable=False),
    sa.Column('current_temp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email', 'seq_num'], ['appliance.email', 'appliance.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'seq_num')
    )
    op.create_table('ac',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('air_handler_seq_num', sa.Integer(), nullable=False),
    sa.Column('EER', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['email', 'air_handler_seq_num'], ['air_handler.email', 'air_handler.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'air_handler_seq_num')
    )
    op.create_table('heat_pump',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('air_handler_seq_num', sa.Integer(), nullable=False),
    sa.Column('SEER', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.Column('HSPF', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['email', 'air_handler_seq_num'], ['air_handler.email', 'air_handler.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'air_handler_seq_num')
    )
    op.create_table('heater',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('air_handler_seq_num', sa.Integer(), nullable=False),
    sa.Column('energy_source', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['email', 'air_handler_seq_num'], ['air_handler.email', 'air_handler.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'air_handler_seq_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heater')
    op.drop_table('heat_pump')
    op.drop_table('ac')
    op.drop_table('water_heater')
    op.drop_table('air_handler')
    op.drop_table('thermal')
    op.drop_table('power_generator')
    op.drop_table('appliance')
    op.drop_table('household')
    op.drop_table('valid_postal')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
