"""initialize models

Revision ID: 170378faa99a
Revises: 
Create Date: 2023-12-19 15:32:45.422330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '170378faa99a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('AC', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index('email', table_name='AC')
    op.drop_constraint('fk_AC_email_Air_Handler_email', 'AC', type_='foreignkey')
    op.create_foreign_key(None, 'AC', 'Household', ['email'], ['email'])
    op.alter_column('Air_Handler', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index('email', table_name='Air_Handler')
    op.drop_constraint('fk_Air_Handler_email_Appliance_email', 'Air_Handler', type_='foreignkey')
    op.create_foreign_key(None, 'Air_Handler', 'Household', ['email'], ['email'])
    op.add_column('Appliance', sa.Column('manufacturer', sa.String(length=256), nullable=False))
    op.alter_column('Appliance', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Appliance', 'model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.drop_index('email', table_name='Appliance')
    op.drop_column('Appliance', 'manufacture')
    op.alter_column('Heat_Pump', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index('email', table_name='Heat_Pump')
    op.drop_constraint('fk_Heat_Pump_email_Air_Handler_email', 'Heat_Pump', type_='foreignkey')
    op.create_foreign_key(None, 'Heat_Pump', 'Household', ['email'], ['email'])
    op.alter_column('Heater', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Heater', 'energy_source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index('email', table_name='Heater')
    op.drop_constraint('fk_Heater_email_Air_Handler_email', 'Heater', type_='foreignkey')
    op.create_foreign_key(None, 'Heater', 'Household', ['email'], ['email'])
    op.alter_column('Household', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Household', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Household', 'postal',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=5),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Household', 'offgrid_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_index('email', table_name='Household')
    op.drop_index('email_2', table_name='Household')
    op.alter_column('Manufacturer', 'manufacturer_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=256),
               nullable=False)
    op.drop_index('manufacturer_name', table_name='Manufacturer')
    op.alter_column('Power_Generator', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Power_Generator', 'avg_kwatts_hr_per_month',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('Power_Generator', 'battery_storage',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('Power_Generator', 'type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index('email', table_name='Power_Generator')
    op.alter_column('Public_Utilities', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Public_Utilities', 'utilities_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               nullable=False)
    op.drop_index('email', table_name='Public_Utilities')
    op.alter_column('Thermal', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Thermal', 'thermal_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.drop_index('email', table_name='Thermal')
    op.alter_column('Valid_Postal', 'postal_code',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=5),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Valid_Postal', 'city',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Valid_Postal', 'state',
               existing_type=mysql.CHAR(collation='utf8mb4_unicode_ci', length=2),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Valid_Postal', 'latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               nullable=True)
    op.alter_column('Valid_Postal', 'longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               nullable=True)
    op.drop_index('postal_code', table_name='Valid_Postal')
    op.alter_column('Water_Heater', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Water_Heater', 'energy_source',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('Water_Heater', 'current_temp',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('email', table_name='Water_Heater')
    op.drop_constraint('fk_Water_Heater_email_Appliance_email', 'Water_Heater', type_='foreignkey')
    op.create_foreign_key(None, 'Water_Heater', 'Household', ['email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Water_Heater', type_='foreignkey')
    op.create_foreign_key('fk_Water_Heater_email_Appliance_email', 'Water_Heater', 'Appliance', ['email', 'seq_num'], ['email', 'seq_num'])
    op.create_index('email', 'Water_Heater', ['email', 'seq_num'], unique=False)
    op.alter_column('Water_Heater', 'current_temp',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Water_Heater', 'energy_source',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.alter_column('Water_Heater', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.create_index('postal_code', 'Valid_Postal', ['postal_code'], unique=False)
    op.alter_column('Valid_Postal', 'longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               nullable=False)
    op.alter_column('Valid_Postal', 'latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               nullable=False)
    op.alter_column('Valid_Postal', 'state',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=2),
               existing_nullable=False)
    op.alter_column('Valid_Postal', 'city',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.alter_column('Valid_Postal', 'postal_code',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=5),
               existing_nullable=False)
    op.create_index('email', 'Thermal', ['email', 'thermal_type'], unique=False)
    op.alter_column('Thermal', 'thermal_type',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=False)
    op.alter_column('Thermal', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.create_index('email', 'Public_Utilities', ['email'], unique=False)
    op.alter_column('Public_Utilities', 'utilities_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               nullable=True)
    op.alter_column('Public_Utilities', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.create_index('email', 'Power_Generator', ['email', 'seq_num'], unique=False)
    op.alter_column('Power_Generator', 'type',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.alter_column('Power_Generator', 'battery_storage',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('Power_Generator', 'avg_kwatts_hr_per_month',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('Power_Generator', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.create_index('manufacturer_name', 'Manufacturer', ['manufacturer_name'], unique=False)
    op.alter_column('Manufacturer', 'manufacturer_name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.create_index('email_2', 'Household', ['email'], unique=False)
    op.create_index('email', 'Household', ['email'], unique=False)
    op.alter_column('Household', 'offgrid_flag',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('Household', 'postal',
               existing_type=sa.String(length=256),
               type_=mysql.CHAR(collation='utf8mb4_unicode_ci', length=5),
               existing_nullable=False)
    op.alter_column('Household', 'type',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.alter_column('Household', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.drop_constraint(None, 'Heater', type_='foreignkey')
    op.create_foreign_key('fk_Heater_email_Air_Handler_email', 'Heater', 'Air_Handler', ['email', 'air_handler_seq_num'], ['email', 'seq_num'])
    op.create_index('email', 'Heater', ['email', 'air_handler_seq_num'], unique=False)
    op.alter_column('Heater', 'energy_source',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.alter_column('Heater', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.drop_constraint(None, 'Heat_Pump', type_='foreignkey')
    op.create_foreign_key('fk_Heat_Pump_email_Air_Handler_email', 'Heat_Pump', 'Air_Handler', ['email', 'air_handler_seq_num'], ['email', 'seq_num'])
    op.create_index('email', 'Heat_Pump', ['email', 'air_handler_seq_num'], unique=False)
    op.alter_column('Heat_Pump', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.add_column('Appliance', sa.Column('manufacture', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250), nullable=False))
    op.create_index('email', 'Appliance', ['email', 'seq_num'], unique=False)
    op.alter_column('Appliance', 'model_name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=True)
    op.alter_column('Appliance', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.drop_column('Appliance', 'manufacturer')
    op.drop_constraint(None, 'Air_Handler', type_='foreignkey')
    op.create_foreign_key('fk_Air_Handler_email_Appliance_email', 'Air_Handler', 'Appliance', ['email', 'seq_num'], ['email', 'seq_num'])
    op.create_index('email', 'Air_Handler', ['email', 'seq_num'], unique=False)
    op.alter_column('Air_Handler', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    op.drop_constraint(None, 'AC', type_='foreignkey')
    op.create_foreign_key('fk_AC_email_Air_Handler_email', 'AC', 'Air_Handler', ['email', 'air_handler_seq_num'], ['email', 'seq_num'])
    op.create_index('email', 'AC', ['email', 'air_handler_seq_num'], unique=False)
    op.alter_column('AC', 'email',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=250),
               existing_nullable=False)
    # ### end Alembic commands ###
