"""rename column name in household: type to household_type

Revision ID: 631e1bf5963f
Revises: eebf83c54343
Create Date: 2023-12-20 20:16:41.904914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '631e1bf5963f'
down_revision: Union[str, None] = 'eebf83c54343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Household', sa.Column('household_type', sa.String(length=256), nullable=False))
    op.drop_column('Household', 'houehole_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Household', sa.Column('houehole_type', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('Household', 'household_type')
    # ### end Alembic commands ###
