"""rename column name in power_generator: avg_kwatts... to kilowatt_hours

Revision ID: 679963c018c7
Revises: 631e1bf5963f
Create Date: 2023-12-20 20:55:05.198348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '679963c018c7'
down_revision: Union[str, None] = '631e1bf5963f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Power_Generator', sa.Column('kilowatt_hours', sa.Integer(), nullable=False))
    op.drop_column('Power_Generator', 'avg_kwatts_hr_per_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Power_Generator', sa.Column('avg_kwatts_hr_per_month', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Power_Generator', 'kilowatt_hours')
    # ### end Alembic commands ###
