"""initialize schema and import postalcode data

Revision ID: 769667df5891
Revises: 
Create Date: 2023-12-20 14:58:32.347268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769667df5891'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Manufacturer',
    sa.Column('manufacturer_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('manufacturer_name')
    )
    op.create_table('Valid_Postal',
    sa.Column('postal_code', sa.CHAR(length=5), nullable=False),
    sa.Column('city', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.PrimaryKeyConstraint('postal_code')
    )
    op.create_table('Household',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('postal', sa.CHAR(length=5), nullable=False),
    sa.Column('sqft', sa.Integer(), nullable=False),
    sa.Column('offgrid_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['postal'], ['Valid_Postal.postal_code'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('Appliance',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=256), nullable=False),
    sa.Column('model_name', sa.String(length=256), nullable=True),
    sa.Column('BTU', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['Household.email'], ),
    sa.ForeignKeyConstraint(['manufacturer'], ['Manufacturer.manufacturer_name'], ),
    sa.PrimaryKeyConstraint('email', 'seq_num')
    )
    op.create_table('Power_Generator',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('avg_kwatts_hr_per_month', sa.Integer(), nullable=False),
    sa.Column('battery_storage', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['Household.email'], ),
    sa.PrimaryKeyConstraint('email', 'seq_num')
    )
    op.create_table('Public_Utilities',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('utilities_type', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['Household.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('Thermal',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('thermal_type', sa.String(length=256), nullable=False),
    sa.Column('setting', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['Household.email'], ),
    sa.PrimaryKeyConstraint('email', 'thermal_type')
    )
    op.create_table('Air_Handler',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('RPM', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email', 'seq_num'], ['Appliance.email', 'Appliance.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'seq_num')
    )
    op.create_table('Water_Heater',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('seq_num', sa.Integer(), nullable=False),
    sa.Column('tank_size', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.Column('energy_source', sa.String(length=256), nullable=False),
    sa.Column('current_temp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email', 'seq_num'], ['Appliance.email', 'Appliance.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'seq_num')
    )
    op.create_table('AC',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('air_handler_seq_num', sa.Integer(), nullable=False),
    sa.Column('EER', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['email', 'air_handler_seq_num'], ['Air_Handler.email', 'Air_Handler.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'air_handler_seq_num')
    )
    op.create_table('Heat_Pump',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('air_handler_seq_num', sa.Integer(), nullable=False),
    sa.Column('SEER', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.Column('HSPF', sa.DECIMAL(precision=10, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['email', 'air_handler_seq_num'], ['Air_Handler.email', 'Air_Handler.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'air_handler_seq_num')
    )
    op.create_table('Heater',
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('air_handler_seq_num', sa.Integer(), nullable=False),
    sa.Column('energy_source', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['email', 'air_handler_seq_num'], ['Air_Handler.email', 'Air_Handler.seq_num'], ),
    sa.PrimaryKeyConstraint('email', 'air_handler_seq_num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Heater')
    op.drop_table('Heat_Pump')
    op.drop_table('AC')
    op.drop_table('Water_Heater')
    op.drop_table('Air_Handler')
    op.drop_table('Thermal')
    op.drop_table('Public_Utilities')
    op.drop_table('Power_Generator')
    op.drop_table('Appliance')
    op.drop_table('Household')
    op.drop_table('Valid_Postal')
    op.drop_table('Manufacturer')
    # ### end Alembic commands ###
