"""seq_num change to autoincrement=true

Revision ID: 7e4d87d705a4
Revises: 231ae57656da
Create Date: 2023-12-28 21:46:19.639118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4d87d705a4'
down_revision: Union[str, None] = '231ae57656da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    op.alter_column('Power_Generator', 'seq_num',
               existing_type=sa.Integer(),
               autoincrement=True)
    op.alter_column('Appliance', 'seq_num',
               existing_type=sa.Integer(),
               autoincrement=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
