"""rename column name in power_generator: type to energy_source

Revision ID: 96944ba5136e
Revises: 679963c018c7
Create Date: 2023-12-20 20:58:07.766282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '96944ba5136e'
down_revision: Union[str, None] = '679963c018c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Power_Generator', sa.Column('energy_source', sa.String(length=256), nullable=False))
    op.drop_column('Power_Generator', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Power_Generator', sa.Column('type', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('Power_Generator', 'energy_source')
    # ### end Alembic commands ###
