"""rename column name in household: type to household_type

Revision ID: eebf83c54343
Revises: 270c12f17116
Create Date: 2023-12-20 20:01:52.451243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eebf83c54343'
down_revision: Union[str, None] = '270c12f17116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Household', sa.Column('houehole_type', sa.String(length=256), nullable=False))
    op.drop_column('Household', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Household', sa.Column('type', mysql.VARCHAR(length=256), nullable=False))
    op.drop_column('Household', 'houehole_type')
    # ### end Alembic commands ###
