"""temperature nullable false change to true in water_heater table

Revision ID: f253035e3c18
Revises: 96944ba5136e
Create Date: 2023-12-20 21:36:38.232543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f253035e3c18'
down_revision: Union[str, None] = '96944ba5136e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Water_Heater', 'current_temp',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Water_Heater', 'current_temp',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
